// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trouble.PL.Data;

#nullable disable

namespace Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    [Migration("20240426175516_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TurnNum")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            GameDate = new DateTime(2024, 4, 26, 12, 55, 15, 676, DateTimeKind.Local).AddTicks(8143),
                            GameName = "Game1",
                            TurnNum = 0
                        },
                        new
                        {
                            Id = new Guid("05efc620-8508-4381-9ab4-369af1daa2c9"),
                            GameDate = new DateTime(2024, 4, 26, 12, 55, 15, 676, DateTimeKind.Local).AddTicks(8201),
                            GameName = "Game2",
                            TurnNum = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblPiece_Id");

                    b.ToTable("tblPiece", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("98719298-427c-412f-b01d-ff0acae7a0ba"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("44fe7a64-ef08-4f19-9387-dc842c7eabb8"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("d311b97c-5054-4f24-83ad-e67d49755d8b"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("0d4a5ade-d268-485d-8372-52cbda3a90a1"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("f6b8e1ba-bf6c-462d-ade4-8d9241bb5d5d"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("448e3e9c-7f34-4685-ab4d-27d25d5ad977"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("262a020a-e281-4e5f-ac3d-b14798168353"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("1927ba14-e4f6-4c55-b554-40c87d2a401e"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("0b45da73-d52b-461d-9e30-6b26e736328a"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("9756029c-1732-479c-a948-91539b2765e2"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("e5abdfde-17e6-45ef-a8cc-55f386045a12"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("5186f3c8-a537-4715-a97e-37961a381204"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("953489bc-0c5b-423b-a230-eb1522da8a28"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("f7b7eb7c-0c1d-4d52-a446-fcad4a0d1f8c"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("e7469172-7a5b-4de2-8180-e99edf430dd4"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("195b292c-0605-484f-a5b4-4f6c4e0db940"),
                            Color = "Yellow"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PieceLocation")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblPieceGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PieceId");

                    b.ToTable("tblPieceGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8b4a464-6888-4c0a-ac0b-23cc25763028"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("98719298-427c-412f-b01d-ff0acae7a0ba"),
                            PieceLocation = 5
                        },
                        new
                        {
                            Id = new Guid("86ac8a0d-db87-4a13-980d-7fff628169b5"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("44fe7a64-ef08-4f19-9387-dc842c7eabb8"),
                            PieceLocation = 2
                        },
                        new
                        {
                            Id = new Guid("203ceed2-e4ba-4aa4-886d-b25d5a972b70"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("d311b97c-5054-4f24-83ad-e67d49755d8b"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("f83f2c70-5cbc-4e9e-9a61-b42b01cf605b"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("0d4a5ade-d268-485d-8372-52cbda3a90a1"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("cf9ea10e-2ec9-40c7-8a0f-55a4a7ae177f"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("f6b8e1ba-bf6c-462d-ade4-8d9241bb5d5d"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("2119aa36-e72f-4267-84cf-9618ecfe0b21"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("448e3e9c-7f34-4685-ab4d-27d25d5ad977"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("cd2894f8-3d8e-4522-a844-5e50a3398f3e"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("262a020a-e281-4e5f-ac3d-b14798168353"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("f07b553a-6f46-4ed1-b28f-dda5b55709c2"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("1927ba14-e4f6-4c55-b554-40c87d2a401e"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("755e3dd4-a138-4fa0-9530-6bcb10927a51"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("0b45da73-d52b-461d-9e30-6b26e736328a"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("2b24976e-5ef9-4a90-b1d0-45a30088afa5"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("9756029c-1732-479c-a948-91539b2765e2"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("2b6a1066-2a76-4d94-b589-172bb5996730"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("e5abdfde-17e6-45ef-a8cc-55f386045a12"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("a5a47f61-2b97-4c64-ad6f-ee67dd9cae4d"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("5186f3c8-a537-4715-a97e-37961a381204"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("3ce67266-6b23-4b2d-aa33-e7e19c304e6b"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("953489bc-0c5b-423b-a230-eb1522da8a28"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("6fdfc1e6-254b-469a-a13f-97d9015df0fc"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("f7b7eb7c-0c1d-4d52-a446-fcad4a0d1f8c"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("a348a6b5-1945-4167-831a-43fac45f5bd2"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("e7469172-7a5b-4de2-8180-e99edf430dd4"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("06224729-76d1-493f-a99a-05a681061bd6"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PieceId = new Guid("195b292c-0605-484f-a5b4-4f6c4e0db940"),
                            PieceLocation = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("07967984-ace6-41c3-899b-92eac5ffb8f6"),
                            FirstName = "Bob",
                            LastName = "Bob",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("bed2c8c8-2363-4d4a-b72b-ca23e959a61b"),
                            FirstName = "Joe",
                            LastName = "Joe",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("38759d29-5ec7-4715-9017-58529fdb917b"),
                            FirstName = "Susan",
                            LastName = "Susan",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("3677e32d-de1f-48af-9c93-57b321836935"),
                            FirstName = "Sally",
                            LastName = "Sally",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("9737d11b-0afa-4760-bfa8-bec07ed4e77a"),
                            FirstName = "Test",
                            LastName = "Test",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User5"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlayerColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52aaf549-51db-461e-bd9e-23aa0f598712"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PlayerColor = "Green",
                            UserId = new Guid("07967984-ace6-41c3-899b-92eac5ffb8f6")
                        },
                        new
                        {
                            Id = new Guid("87a71e8d-7509-4360-becf-5d9e112b52e4"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PlayerColor = "Yellow",
                            UserId = new Guid("bed2c8c8-2363-4d4a-b72b-ca23e959a61b")
                        },
                        new
                        {
                            Id = new Guid("73f4652e-6dc0-49ca-ad33-cecf7365509f"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PlayerColor = "Blue",
                            UserId = new Guid("38759d29-5ec7-4715-9017-58529fdb917b")
                        },
                        new
                        {
                            Id = new Guid("ff3a296b-7d53-4f00-b051-7336f5ea41cf"),
                            GameId = new Guid("3d02117a-4051-460a-ba4d-baf5d4e583be"),
                            PlayerColor = "Red",
                            UserId = new Guid("3677e32d-de1f-48af-9c93-57b321836935")
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblPiece", "Piece")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_PieceId");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblPieceGames");

                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Navigation("tblPieceGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
