// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trouble.PL.Data;

#nullable disable

namespace Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    [Migration("20240424194602_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TurnNum")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            GameDate = new DateTime(2024, 4, 24, 14, 46, 1, 516, DateTimeKind.Local).AddTicks(4078),
                            GameName = "Game1",
                            TurnNum = 0
                        },
                        new
                        {
                            Id = new Guid("ffb33984-9bf9-4b4c-9668-c9883c780a83"),
                            GameDate = new DateTime(2024, 4, 24, 14, 46, 1, 516, DateTimeKind.Local).AddTicks(4114),
                            GameName = "Game2",
                            TurnNum = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblPiece_Id");

                    b.ToTable("tblPiece", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("42387750-418a-4f64-89ff-74b0c39f2b26"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("cb11515d-5b07-4180-9533-3df19aab7ee2"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("fc9c24aa-8efa-43e3-9e8d-83338625372f"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("09e29f5d-1482-480d-8da1-9ab63fb69f7f"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("e991a08a-34d7-467a-8deb-a3d8e82c2fec"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("cdbbf73c-2775-41ee-9acf-a84a98af1d6e"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("6c634491-9525-4cd8-bccd-5577e33598bf"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("57406578-e967-4fad-bf96-23357089199e"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("3eba5e4b-fbbe-484f-856d-c15e19f3c0c4"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("4ea9180d-4603-4893-aea1-6f8dac7cfb37"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("201c3dbc-a481-4634-b353-f51708250be2"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("af39def9-b6a5-45bc-ab46-ac572807a8c9"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("7ea1db8a-7199-4d24-a4cd-aa1d8b7d71a3"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("9f1bbe17-debb-4882-9726-6831cdf56100"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("351d2af1-21af-4ec5-8ce2-e7e5589d9769"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("83ee0fcb-75ec-420e-a777-5614b9d47da3"),
                            Color = "Yellow"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PieceLocation")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblPieceGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PieceId");

                    b.ToTable("tblPieceGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7511583b-1a94-44de-b5d2-fa1f1195ef38"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("42387750-418a-4f64-89ff-74b0c39f2b26"),
                            PieceLocation = 5
                        },
                        new
                        {
                            Id = new Guid("8288ad83-e67a-46b3-b8d3-36fa94b3686a"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("cb11515d-5b07-4180-9533-3df19aab7ee2"),
                            PieceLocation = 2
                        },
                        new
                        {
                            Id = new Guid("d215dc4a-bdd2-4dd1-85eb-35528d197d73"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("fc9c24aa-8efa-43e3-9e8d-83338625372f"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("ed48f325-83a2-48dc-b34d-b35c3183f93f"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("09e29f5d-1482-480d-8da1-9ab63fb69f7f"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("5e0a857c-8bf7-4a19-8c26-b2746260d0c6"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("e991a08a-34d7-467a-8deb-a3d8e82c2fec"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("02fa0cf7-5cb2-49c3-921b-eb5481a500c7"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("cdbbf73c-2775-41ee-9acf-a84a98af1d6e"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("899acd33-9d67-4dc2-b7b4-a8508959e1df"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("6c634491-9525-4cd8-bccd-5577e33598bf"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("cf456720-51e3-4112-bec7-e94da7adbc35"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("57406578-e967-4fad-bf96-23357089199e"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("0f6c19cf-8063-466d-9207-c0f75712c527"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("3eba5e4b-fbbe-484f-856d-c15e19f3c0c4"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("922cbef6-64ef-4cc6-9bc7-ab19ac2a7ec3"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("4ea9180d-4603-4893-aea1-6f8dac7cfb37"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("7c3402c8-2ac4-443e-9e2f-37b28f6a98eb"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("201c3dbc-a481-4634-b353-f51708250be2"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("1df61e2a-25d8-49a2-af52-fd8f67689405"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("af39def9-b6a5-45bc-ab46-ac572807a8c9"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("bc54024f-39bd-46be-bae7-5426a94a4b71"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("7ea1db8a-7199-4d24-a4cd-aa1d8b7d71a3"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("2bc05284-51b0-45a4-af35-1d563a5d392f"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("9f1bbe17-debb-4882-9726-6831cdf56100"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("49014f9f-33e6-409c-9f19-5559d9b9fb87"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("351d2af1-21af-4ec5-8ce2-e7e5589d9769"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("c87f3b50-58d1-4f3f-bd25-4ea6d2076779"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            PieceId = new Guid("83ee0fcb-75ec-420e-a777-5614b9d47da3"),
                            PieceLocation = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e65103e-af27-4657-9a65-2a21957d55f9"),
                            FirstName = "Bob",
                            LastName = "Bob",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("e03f19b7-e8aa-4b73-8b74-e1baa5532b58"),
                            FirstName = "Joe",
                            LastName = "Joe",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("34b435a4-1c4c-4671-987f-ca0d6d51cd95"),
                            FirstName = "Susan",
                            LastName = "Susan",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("525d567f-dbbd-4576-b4ea-eb9a3452c0e1"),
                            FirstName = "Sally",
                            LastName = "Sally",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("921b3ceb-a6c6-43e1-a353-d8a4f3047412"),
                            FirstName = "Test",
                            LastName = "Test",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User5"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52669b8e-34b2-496e-9564-ef46e3baac50"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            UserId = new Guid("0e65103e-af27-4657-9a65-2a21957d55f9")
                        },
                        new
                        {
                            Id = new Guid("da9c5fb9-e55e-42d3-b666-c00a1ea004c1"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            UserId = new Guid("e03f19b7-e8aa-4b73-8b74-e1baa5532b58")
                        },
                        new
                        {
                            Id = new Guid("0d23ab6b-10a2-4f4e-a02f-a5f1db12690d"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            UserId = new Guid("34b435a4-1c4c-4671-987f-ca0d6d51cd95")
                        },
                        new
                        {
                            Id = new Guid("d41e79f8-cb12-4efe-8d13-18ad9678330b"),
                            GameId = new Guid("d20228c1-e0b5-4dc7-b7dd-014414397feb"),
                            UserId = new Guid("525d567f-dbbd-4576-b4ea-eb9a3452c0e1")
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblPiece", "Piece")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_PieceId");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblPieceGames");

                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Navigation("tblPieceGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
