// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trouble.PL.Data;

#nullable disable

namespace Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    [Migration("20240223002745_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TurnNum")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            GameDate = new DateTime(2024, 2, 22, 18, 27, 44, 894, DateTimeKind.Local).AddTicks(4289),
                            GameName = "Game1",
                            TurnNum = 0
                        },
                        new
                        {
                            Id = new Guid("c1fb3ac8-f030-463c-96c1-50b697b9c534"),
                            GameDate = new DateTime(2024, 2, 22, 18, 27, 44, 894, DateTimeKind.Local).AddTicks(4330),
                            GameName = "Game2",
                            TurnNum = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblPiece_Id");

                    b.ToTable("tblPiece", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd521ce-1af8-4d5d-8b94-7599a222c5e8"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("f6d8a402-4d63-4202-a23a-c519377d0a23"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("d50d0698-d19d-4fcc-bedb-cffe17283bd2"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("cdc863ab-47fb-49b5-babf-319213a168e8"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("1b9dcf9a-af53-4ade-8642-24ae7e73b8bd"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("74520448-c375-4ee9-ba6f-07ebf65c8136"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("3341930b-0940-4dc1-9e3b-ef83da5e4c1d"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("77243022-b823-406f-924f-6164e4321eca"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("069e4efa-10b3-4727-9cf7-083d96e9565c"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("a7933241-0931-4537-8516-2bb56bdb69d4"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("5596cd68-0b52-4bb7-86d0-4f9d1c03ffb1"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("846435a1-4329-4d82-8c67-24ac95bb214d"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("d560299a-ce8b-4296-b66d-e8df03fdb258"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("7d3f05f2-7b7e-461c-9ec8-9365a6ea8f81"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("15f7c95e-85df-4f1f-9483-dc1206f9a49d"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("d1d95e3f-641a-4b8e-adb0-29c73069b7bf"),
                            Color = "Yellow"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PieceLocation")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblPieceGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PieceId");

                    b.ToTable("tblPieceGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9265f1c5-8937-4fa9-b015-c74e4541ef01"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("7bd521ce-1af8-4d5d-8b94-7599a222c5e8"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("b70eae81-f04f-4087-8f6f-b83d1171f38e"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("f6d8a402-4d63-4202-a23a-c519377d0a23"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("9ed51244-1822-454e-b223-ecf4955d30a6"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("d50d0698-d19d-4fcc-bedb-cffe17283bd2"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("643aaae8-ef23-4932-967b-c9df34b9fe7d"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("cdc863ab-47fb-49b5-babf-319213a168e8"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("2f08b679-0133-4ecb-85c7-3fbb5458c5a0"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("1b9dcf9a-af53-4ade-8642-24ae7e73b8bd"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("449eee02-5494-402b-a7e9-86a129d3560b"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("74520448-c375-4ee9-ba6f-07ebf65c8136"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("b29d5c07-5817-4388-ae6f-fbced3ea2f8a"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("3341930b-0940-4dc1-9e3b-ef83da5e4c1d"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("cc118926-adfb-4a72-b692-6df84ed93855"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("77243022-b823-406f-924f-6164e4321eca"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("d8bee404-e0f6-4226-b963-18560b388968"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("069e4efa-10b3-4727-9cf7-083d96e9565c"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("836b5140-9f2c-4c81-b324-e6f5ef647f1b"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("a7933241-0931-4537-8516-2bb56bdb69d4"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("0274f949-caf7-4645-932f-ce9e7b733d7b"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("5596cd68-0b52-4bb7-86d0-4f9d1c03ffb1"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("6dd59b06-0907-47d5-a923-547458c73dfb"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("846435a1-4329-4d82-8c67-24ac95bb214d"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("4c08c194-1adb-459a-8674-59adb1b2d135"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("d560299a-ce8b-4296-b66d-e8df03fdb258"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("719c8975-8f95-4ba9-9d3f-0b3d81ce1143"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("7d3f05f2-7b7e-461c-9ec8-9365a6ea8f81"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("004fdff7-f39e-494b-90fb-242439680b58"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("15f7c95e-85df-4f1f-9483-dc1206f9a49d"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("0f0838d2-17ae-455c-b245-e66a7d68d19d"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            PieceId = new Guid("d1d95e3f-641a-4b8e-adb0-29c73069b7bf"),
                            PieceLocation = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4df8fe47-9d3f-4c75-ab9e-a9f1970acf2b"),
                            FirstName = "Bob",
                            LastName = "Bob",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("7e05634a-a83b-4ef1-9f11-ebda6bcbca12"),
                            FirstName = "Joe",
                            LastName = "Joe",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("722246c2-1979-4e57-a6b5-28269210d6e5"),
                            FirstName = "Susan",
                            LastName = "Susan",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("d73c567d-66e5-4998-8757-7ac78f270e00"),
                            FirstName = "Sally",
                            LastName = "Sally",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("ab249eb8-ec98-4dd3-83a6-e2761cfe3001"),
                            FirstName = "Test",
                            LastName = "Test",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User5"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac1e7d6e-45e0-4d90-830c-f939e48913ee"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            UserId = new Guid("4df8fe47-9d3f-4c75-ab9e-a9f1970acf2b")
                        },
                        new
                        {
                            Id = new Guid("703d999d-42f6-4b93-8f08-ce3bb0d8af08"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            UserId = new Guid("7e05634a-a83b-4ef1-9f11-ebda6bcbca12")
                        },
                        new
                        {
                            Id = new Guid("79c120db-4866-4ea8-8f5f-af819652105a"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            UserId = new Guid("722246c2-1979-4e57-a6b5-28269210d6e5")
                        },
                        new
                        {
                            Id = new Guid("dfa059f4-f78a-4461-aa87-c62e41c7c82e"),
                            GameId = new Guid("9f6f4f9b-e52d-4ffa-8ae2-a42af7f3d1b5"),
                            UserId = new Guid("d73c567d-66e5-4998-8757-7ac78f270e00")
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblPiece", "Piece")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_PieceId");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblPieceGames");

                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Navigation("tblPieceGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
