// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trouble.PL.Data;

#nullable disable

namespace Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    partial class TroubleEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TurnNum")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            GameDate = new DateTime(2024, 2, 22, 19, 24, 44, 746, DateTimeKind.Local).AddTicks(8427),
                            GameName = "Game1",
                            TurnNum = 0
                        },
                        new
                        {
                            Id = new Guid("373529ca-49a8-455a-b45d-e6e5ecc295ea"),
                            GameDate = new DateTime(2024, 2, 22, 19, 24, 44, 746, DateTimeKind.Local).AddTicks(8468),
                            GameName = "Game2",
                            TurnNum = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblPiece_Id");

                    b.ToTable("tblPiece", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2a208dd-34dd-4cc2-9384-75e86d1336f2"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("93681a93-a7b5-4924-a630-37bfcdf62429"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("a0306e1e-f8eb-45c6-874b-fb6c01405630"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("0c8ec1b3-2eff-4f99-8cfa-db7e8e9527d3"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("28a6c166-5ed7-4186-81b2-bbaf7c9560bd"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("4369f643-f157-4d34-8524-0b9cf4c0b7f6"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("078eb18a-9b7b-4582-a6d4-44030d628812"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("2bdf38d3-45f3-45a1-a81e-e66cc726a02d"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("61f13faa-7765-452f-aa76-c37c5126d2c9"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("010152c6-7f33-404e-94f0-7e8d1f62e47a"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("48891ff0-b047-43f7-b638-52932c818704"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("9cd75a94-0c62-4915-8212-8d58605608f4"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("711485d1-1d0e-4943-9cdc-30493ffac938"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("fa200e39-0418-4a0c-81aa-559a9d90bdd9"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("56d8efdc-d403-4a64-a6c5-bfbaed13aa4a"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("445c9c75-0c69-4616-b68f-a4d07ab4b674"),
                            Color = "Yellow"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PieceLocation")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblPieceGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PieceId");

                    b.ToTable("tblPieceGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8db3466-6c8b-416d-b22c-1a4acdc13cf1"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("a2a208dd-34dd-4cc2-9384-75e86d1336f2"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("6cc710f1-2db6-4462-9965-ab4ac9375353"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("93681a93-a7b5-4924-a630-37bfcdf62429"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("1e182670-129b-4fba-8a5d-d2465c2e3ebe"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("a0306e1e-f8eb-45c6-874b-fb6c01405630"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("4594e3c9-e1ab-4c91-91d9-916749f11391"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("0c8ec1b3-2eff-4f99-8cfa-db7e8e9527d3"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("ba47ef09-4d7d-4444-b7ae-6cbaee86e801"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("28a6c166-5ed7-4186-81b2-bbaf7c9560bd"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("3bb10e12-895d-4f10-a447-f0466fa4eb2c"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("4369f643-f157-4d34-8524-0b9cf4c0b7f6"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("4dc9a535-4324-4b26-8a76-2ef931645694"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("078eb18a-9b7b-4582-a6d4-44030d628812"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("4771a29d-55cd-47d5-995b-345d678b05ce"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("2bdf38d3-45f3-45a1-a81e-e66cc726a02d"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("87d98eb5-2450-44ae-a75a-4d96c2003d54"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("61f13faa-7765-452f-aa76-c37c5126d2c9"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("baf42e0e-0317-4acc-8485-a4a5f7d16ff5"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("010152c6-7f33-404e-94f0-7e8d1f62e47a"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("5b1515d2-c83d-4242-ab23-658f7bb05089"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("48891ff0-b047-43f7-b638-52932c818704"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("0d1c9ce9-9ddf-4683-8e02-9e18c6247188"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("9cd75a94-0c62-4915-8212-8d58605608f4"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("02673ad7-cfe9-44bc-b0df-2deecf7086b3"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("711485d1-1d0e-4943-9cdc-30493ffac938"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("581bc473-3359-47fd-8f5e-b02c4593adc9"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("fa200e39-0418-4a0c-81aa-559a9d90bdd9"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("0b62745f-8112-47aa-82b5-820ce8c61517"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("56d8efdc-d403-4a64-a6c5-bfbaed13aa4a"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("fde3b46a-d053-4afa-aa13-d0471d467aa5"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            PieceId = new Guid("445c9c75-0c69-4616-b68f-a4d07ab4b674"),
                            PieceLocation = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a004861-517d-400b-9665-d8b79225658e"),
                            FirstName = "Bob",
                            LastName = "Bob",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("f9301289-cf75-4af6-b468-a3b1bf051933"),
                            FirstName = "Joe",
                            LastName = "Joe",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("374350c0-48eb-4a9d-b1c6-8154c39e09db"),
                            FirstName = "Susan",
                            LastName = "Susan",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("e45eca0c-5e5e-4cfd-a54a-db9af4d559ab"),
                            FirstName = "Sally",
                            LastName = "Sally",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User4"
                        },
                        new
                        {
                            Id = new Guid("6911a7d5-eb1f-489e-8231-1126623c0ae5"),
                            FirstName = "Test",
                            LastName = "Test",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User5"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee0af0c9-7a1f-4914-95c0-d240c6a7b477"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            UserId = new Guid("2a004861-517d-400b-9665-d8b79225658e")
                        },
                        new
                        {
                            Id = new Guid("65bcc509-9fcf-4876-8d5d-91c17c905c8d"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            UserId = new Guid("f9301289-cf75-4af6-b468-a3b1bf051933")
                        },
                        new
                        {
                            Id = new Guid("1b6b1550-a495-4afa-af4a-6a260bb229d7"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            UserId = new Guid("374350c0-48eb-4a9d-b1c6-8154c39e09db")
                        },
                        new
                        {
                            Id = new Guid("924fcd12-b885-49a4-8977-88fe0d1af712"),
                            GameId = new Guid("00c76cb1-3c3f-44b1-a7e3-a64df5e4a11e"),
                            UserId = new Guid("e45eca0c-5e5e-4cfd-a54a-db9af4d559ab")
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblPiece", "Piece")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_PieceId");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblPieceGames");

                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Navigation("tblPieceGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
