// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trouble.PL.Data;

#nullable disable

namespace Trouble.PL.Migrations
{
    [DbContext(typeof(TroubleEntities))]
    partial class TroubleEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TurnNum")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblGame_Id");

                    b.ToTable("tblGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            GameDate = new DateTime(2024, 2, 22, 14, 47, 35, 201, DateTimeKind.Local).AddTicks(5507),
                            GameName = "Game1",
                            TurnNum = 0
                        },
                        new
                        {
                            Id = new Guid("ee20e0c2-9433-407a-9e88-be95273b9f96"),
                            GameDate = new DateTime(2024, 2, 22, 14, 47, 35, 201, DateTimeKind.Local).AddTicks(5561),
                            GameName = "Game2",
                            TurnNum = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.HasKey("Id")
                        .HasName("PK_tblPiece_Id");

                    b.ToTable("tblPiece", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("207af9d3-fae3-4f67-8346-b0a16a313c4b"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("d8df6cf8-98e4-4805-baed-488aeef42f63"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("16ca0950-3ed6-4c9f-a6fd-6dfdc1917979"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("4cca7de6-1658-407d-9f45-4387ceca01b1"),
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("1db5564f-e1e4-4810-9078-7f51768d1afa"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("142f44e8-fde7-426b-ab5d-8ac2837b62b5"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("6eb61891-d0a8-4ce1-ba81-05543abb8451"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("6820cfc6-2f41-46c5-ae4d-4af90c542509"),
                            Color = "Blue"
                        },
                        new
                        {
                            Id = new Guid("708b722f-235a-4962-ba50-e9187e5d1a7f"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("588e54b6-596c-430f-aee0-0f46cdb31ed1"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("cc9a1056-056d-42f5-bc0d-8a909fc628b5"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("a6f181e3-257e-467d-9e88-889726693835"),
                            Color = "Green"
                        },
                        new
                        {
                            Id = new Guid("9cc5765e-6be9-4010-ba98-11dafd6c94aa"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("3f03e840-0523-43e5-b723-1f386edc8c6e"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("e419ed30-b259-4816-a2f0-889bef73fd65"),
                            Color = "Yellow"
                        },
                        new
                        {
                            Id = new Guid("d03ed69a-1acb-41f1-9bac-73619d30dcf4"),
                            Color = "Yellow"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PieceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PieceLocation")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblPieceGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PieceId");

                    b.ToTable("tblPieceGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("de2bcdc7-34e3-41a7-b30d-9b7a637c9007"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("207af9d3-fae3-4f67-8346-b0a16a313c4b"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("7001b39f-96f4-4694-9cdc-dcd7067c144f"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("d8df6cf8-98e4-4805-baed-488aeef42f63"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("65723929-0c54-4fd1-8e11-f596fdcb2451"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("16ca0950-3ed6-4c9f-a6fd-6dfdc1917979"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("703a85e2-dc17-443f-8ffb-2dc283ca6a43"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("4cca7de6-1658-407d-9f45-4387ceca01b1"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("07cbae2e-700b-44f9-bb41-360f95355b74"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("1db5564f-e1e4-4810-9078-7f51768d1afa"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("9bf27216-d6f8-43a1-94e7-173185d684a4"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("142f44e8-fde7-426b-ab5d-8ac2837b62b5"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("fa894c25-2e93-45c0-a954-9692bb3130a3"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("6eb61891-d0a8-4ce1-ba81-05543abb8451"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("ff805459-5187-44d9-9ce2-851424322fc2"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("6820cfc6-2f41-46c5-ae4d-4af90c542509"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("a2c01408-5202-4739-813d-84fc1276859a"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("708b722f-235a-4962-ba50-e9187e5d1a7f"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("edab3310-2a1d-497a-9e39-e0a0721257e5"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("588e54b6-596c-430f-aee0-0f46cdb31ed1"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("b8cbb831-eb9a-44e0-be89-40dbda955411"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("cc9a1056-056d-42f5-bc0d-8a909fc628b5"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("7797ed61-ce9d-46b9-8469-7bd20421c9c2"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("a6f181e3-257e-467d-9e88-889726693835"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("b7a48085-e93d-4203-b76e-70479e61c0ba"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("9cc5765e-6be9-4010-ba98-11dafd6c94aa"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("39cefd86-0b50-4d03-853f-fdd7c551783d"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("3f03e840-0523-43e5-b723-1f386edc8c6e"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("748c875f-6f1e-43db-a306-9dd11788fef8"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("e419ed30-b259-4816-a2f0-889bef73fd65"),
                            PieceLocation = 0
                        },
                        new
                        {
                            Id = new Guid("cce42d14-1250-4980-8b20-38fd7e205238"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            PieceId = new Guid("d03ed69a-1acb-41f1-9bac-73619d30dcf4"),
                            PieceLocation = 0
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0be3986f-ad9b-4d96-8b44-1605704f825b"),
                            FirstName = "Bob",
                            LastName = "Bob",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User1"
                        },
                        new
                        {
                            Id = new Guid("a7d0b8c1-de62-45eb-b725-769d10a09c1b"),
                            FirstName = "Joe",
                            LastName = "Joe",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User2"
                        },
                        new
                        {
                            Id = new Guid("d3b02c06-95cb-476a-871b-bc829b6fba88"),
                            FirstName = "Susan",
                            LastName = "Susan",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User3"
                        },
                        new
                        {
                            Id = new Guid("e473cd68-620e-40d3-90b8-d7cecd019674"),
                            FirstName = "Sally",
                            LastName = "Sally",
                            Password = "ZAqyuuB77cTBY/Z5p0b3q3+10fo=",
                            Username = "User4"
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblUserGame_Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("tblUserGame", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("abd9d242-08a2-4a85-bcc5-00d26dcc8179"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            UserId = new Guid("0be3986f-ad9b-4d96-8b44-1605704f825b")
                        },
                        new
                        {
                            Id = new Guid("ecf930ae-b52d-4ebe-ac91-614f0c20ab63"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            UserId = new Guid("a7d0b8c1-de62-45eb-b725-769d10a09c1b")
                        },
                        new
                        {
                            Id = new Guid("b173598c-1c84-4b18-8f8a-7ce1ecafad48"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            UserId = new Guid("d3b02c06-95cb-476a-871b-bc829b6fba88")
                        },
                        new
                        {
                            Id = new Guid("9c799434-4b49-4393-ae77-9133379fdbdf"),
                            GameId = new Guid("c6337b55-4370-4965-9508-34de26361787"),
                            UserId = new Guid("e473cd68-620e-40d3-90b8-d7cecd019674")
                        });
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPieceGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblPiece", "Piece")
                        .WithMany("tblPieceGames")
                        .HasForeignKey("PieceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblPieceGame_PieceId");

                    b.Navigation("Game");

                    b.Navigation("Piece");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUserGame", b =>
                {
                    b.HasOne("Trouble.PL.Entities.tblGame", "Game")
                        .WithMany("tblUserGames")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_GameId");

                    b.HasOne("Trouble.PL.Entities.tblUser", "User")
                        .WithMany("tblUserGames")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_tblUserGame_UserId");

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblGame", b =>
                {
                    b.Navigation("tblPieceGames");

                    b.Navigation("tblUserGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblPiece", b =>
                {
                    b.Navigation("tblPieceGames");
                });

            modelBuilder.Entity("Trouble.PL.Entities.tblUser", b =>
                {
                    b.Navigation("tblUserGames");
                });
#pragma warning restore 612, 618
        }
    }
}
